"""update email

Revision ID: 526a373132fa
Revises: 381611e0fead
Create Date: 2024-04-29 19:03:55.312297

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526a373132fa"
down_revision: Union[str, None] = "381611e0fead"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "email")
    # ### end Alembic commands ###
