"""colocando img_url no produto

Revision ID: e0723f9712dc
Revises: 409531a80776
Create Date: 2024-07-09 23:50:01.250685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0723f9712dc'
down_revision = '409531a80776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_product')
    # ### end Alembic commands ###